


apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  vaultRole: "{{ .Values.client_name }}-role"
  data:
  - key: "{{ .Values.client_name }}/data/{{ .Values.client_name }}"
    name: matan
    property: matan
