apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-app-route
spec:
  host: "es-demo.{{ .Values.OC_APP_PATH }}"
  to:
    kind: Service
    name: my-service
  port:
    targetPort: 5000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
